
services:
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: august-minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"       # Minecraft Game Port
      - "24454:24454/udp"   # Simple Voice Chat Port (UDP required!)
      - "8100:8100"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4"
      MEMORY: ${SERVER_MEMORY}
      MAX_PLAYERS: ${SERVER_MAX_PLAYERS}
      ONLINE_MODE: ${SERVER_ONLINE_MODE}
      WHITE_LIST: ${SERVER_WHITELIST}

      # Server Settings & Customization
      MOTD: ${SERVER_MOTD}
      SERVER_NAME: ${SERVER_NAME}
      DIFFICULTY: ${SERVER_DIFFICULTY}
      MODE: ${SERVER_MODE}
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      VIEW_DISTANCE: ${SERVER_VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${SERVER_SIMULATION_DISTANCE}

      ENABLE_RCON: ${ENABLE_RCON}
      RCON_PORT: ${RCON_PORT}
      RCON_PASSWORD: ${RCON_PASSWORD}

      CF_FORCE_SYNCH: "true"
      WORLD: ${WORLD_NAME}
      SEED: ${WORLD_SEED}
      PVP: ${WORLD_PVP}
      ALLOW_FLIGHT: ${WORLD_ALLOW_FLIGHT}
      
      # Auto Pause (Saves CPU when no players are online)
      ENABLE_AUTOPAUSE: ${SERVER_ENABLE_AUTOPAUSE}        # Can be set to "true", but sometimes interferes with tick-based modded machines


    volumes:
      - ./data:/data

    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m